EMS_MVC/Models/Department.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMS_MVC.Models
{
    public class Department
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [Required(ErrorMessage = "Please input a name")]
        public string Name { get; set; }
        public List<Employee>? Employees { get; set; }

        public Department()
        {

        }

        public Department(int id, string name)
        {
            ID = id;
            Name = name;
        }
    }
}

EMS_MVC/Models/Employee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMS_MVC.Models
{
    public class Employee
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [Required(ErrorMessage = "Please input a name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please input a date.")]
        public DateTime DateOfBirth { get; set; }
        [EmailAddress(ErrorMessage = "This is not a valid email address.")]
        public string Email { get; set; }
        [RegularExpression("(09)[0-9]{9}", ErrorMessage = "This is not a valid phone number")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public int DepartmentID { get; set; }
        public Department? Department { get; set; }

        public Employee()
        {

        }

        public Employee(int iD, string name, DateTime dateOfBirth, string email, string phone, int departmentID)
        {
            ID = iD;
            Name = name;
            DateOfBirth = dateOfBirth;
            Email = email;
            Phone = phone;
            DepartmentID = departmentID;
        }
    }
}

EMS_MVC/Models/ErrorViewModel.cs
namespace EMS_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EMS_MVC/Controllers/DepartmentController.cs
using EMS_MVC.Repository;
using EMS_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EMS_MVC.Controllers
{
    public class DepartmentController : Controller
    {
        IEMSRepoDepartment _repo;
        //IRepoDeptInMemory _repoDept;
        //IRepoEmpInMemory _repoEmp;

        public DepartmentController(IEMSRepoDepartment repo)
        {
            this._repo = repo;
        }

        public IActionResult ViewAllDepartments()
        {
            var DeptList = _repo.ViewAllDepartments();
            return View(DeptList);
        }

        public IActionResult ViewOneDepartment(int id)
        {
            var Dept = _repo.ViewOneDepartment(id);
            return View(Dept);
        }
        [HttpGet]
        public IActionResult AddDepartment()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddDepartment(Department NewDepartment)
        {
            if (ModelState.IsValid)
            {
                var NewDept = _repo.AddDepartment(NewDepartment);
                return RedirectToAction("ViewAllDepartments");
            }
            return View();
        }
        [HttpGet]
        public IActionResult UpdateDepartment(int id)
        {
            var OldDept = _repo.ViewOneDepartment(id);
            return View(OldDept);
        }
        [HttpPost]
        public IActionResult UpdateDepartment(Department NewDepartment)
        {
            if (ModelState.IsValid)
            {
                var NewDept = _repo.UpdateDepartment(NewDepartment);
                return RedirectToAction("ViewAllDepartments");
            }

            return View();
        }

        public IActionResult DeleteDepartment(int id)
        {
            _repo.DeleteDepartment(id);
            return RedirectToAction("ViewAllDepartments");
        }
    }
}

EMS_MVC/Controllers/EmployeeController.cs
using EMS_MVC.Models;
using EMS_MVC.Repository;
using Microsoft.AspNetCore.Mvc;

namespace EMS_MVC.Controllers
{
    public class EmployeeController : Controller
    {

        IEMSRepoEmployee _repo;
        //IRepoEmpInMemory _repoEmp;
        //IRepoDeptInMemory _repoDept;

        public EmployeeController(IEMSRepoEmployee repo)
        {
            this._repo = repo;
        }

        public IActionResult ViewAllEmployees()
        {
            var EmpList = _repo.ViewAllEmployees();
            return View(EmpList);
        }

        public IActionResult ViewOneEmployee(int id)
        {
            var Emp = _repo.ViewOneEmployee(id);
            return View(Emp);
        }
        [HttpGet]
        public IActionResult AddEmployee()
        {
            var deptList = _repo.FetchDepartmentList();
            ViewBag.Departments = deptList;

            return View();
        }
        [HttpPost]
        public IActionResult AddEmployee(Employee NewEmployee)
        {
            if (ModelState.IsValid)
            {
                var NewEmp = _repo.AddEmployee(NewEmployee);
                return RedirectToAction("ViewAllEmployees");
            }
            return View();
        }
        [HttpGet]
        public IActionResult UpdateEmployee(int id)
        {
            var deptList = _repo.FetchDepartmentList();
            ViewBag.Departments = deptList;

            var OldEmp = _repo.ViewOneEmployee(id);
            return View(OldEmp);
        }
        [HttpPost]
        public IActionResult UpdateEmployee(Employee NewEmployee)
        {
            if (ModelState.IsValid)
            {
                var NewEmp = _repo.UpdateEmployee(NewEmployee);
                return RedirectToAction("ViewAllEmployees");
            }

            return View();
        }

        public IActionResult DeleteEmployee(int id)
        {
            _repo.DeleteEmployee(id);
            return RedirectToAction("ViewAllEmployees");
        }
    }
}

EMS_MVC/Controllers/HomeController.cs
using EMS_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EMS_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EMS_MVC/Views/Department/AddDepartment.cshtml
@model Department

<h3 align="center"> Create Department</h3>

<form method="post" asp-action="AddDepartment" asp-controller="Department">

    <div class="mb-3">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

EMS_MVC/Views/Department/UpdateDepartment.cshtml
@model Department

<h3 align = "center"> Update Department</h3>

<form method="post" asp-action="UpdateDepartment" asp-controller="Department">

    <div class="mb-3">
        <label class="form-label" asp-for="ID"></label>
        <input class="form-control" asp-for="ID" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

EMS_MVC/Views/Department/ViewAllDepartments.cshtml
@model List<Department>


<h3 align="center">Departments List</h3>

<a class="btn btn-success" asp-action="AddDepartment" asp-controller="Department">Add Department</a>

<table class="table table-striped table-info">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Dept in Model)
        {
            <tr>
                <th scope="row">@Dept.ID</th>
                <td>@Dept.Name</td>
                <td><a class="btn btn-primary" asp-controller="Department" asp-action="ViewOneDepartment" asp-route-id="@Dept.ID">View</a></td>
                <td><a class="btn btn-warning" asp-controller="Department" asp-action="UpdateDepartment" asp-route-id="@Dept.ID">Edit</a></td>
                <td><a class="btn btn-danger" asp-controller="Department" asp-action="DeleteDepartment" asp-route-id="@Dept.ID">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

EMS_MVC/Views/Department/ViewOneDepartment.cshtml
@model Department

<h1>Department Details</h1>

<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <h6 class="card-subtitle mb-2 text-muted">@Model.ID</h6>
        <a asp-controller="Department" asp-action="ViewAllDepartments" class="card-link">Back to list</a>
    </div>
</div>

EMS_MVC/Views/Employee/AddEmployee.cshtml
@model Employee

<h3 align="center"> Add Employee</h3>

<form method="post" asp-action="AddEmployee" asp-controller="Employee">

    <div class="mb-3">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="DateOfBirth">Date of Birth</label>
        <input type="date" class="form-control" asp-for="DateOfBirth" />
        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Email">Email Address</label>
        <input type="email" class="form-control" asp-for="Email" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Phone">Phone Number (Mobile)</label>
        <input class="form-control" asp-for="Phone" />
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>

    <label class="form-label" asp-for="DepartmentID">Department</label>
    @Html.DropDownListFor(x => x.DepartmentID, new SelectList(ViewBag.Departments, "ID", "Name"), new {@class = "form-control"})
    <span asp-validation-for="DepartmentID" class="text-danger"></span>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

EMS_MVC/Views/Employee/UpdateEmployee.cshtml
@model Employee

<h3 align="center"> Update Employee</h3>

<form method="post" asp-action="UpdateEmployee" asp-controller="Employee">

    <div class="mb-3">
        <label class="form-label" asp-for="ID"></label>
        <input class="form-control" asp-for="ID" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="DateOfBirth"></label>
        <input type ="date" class="form-control" asp-for="DateOfBirth" />
        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Email"></label>
        <input type ="email" class="form-control" asp-for="Email" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Phone"></label>
        <input class="form-control" asp-for="Phone" />
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>
    <label class="form-label" asp-for="DepartmentID">Department</label>
    @Html.DropDownListFor(x => x.DepartmentID, new SelectList(ViewBag.Departments, "ID", "Name"), new {@class = "form-control"})
    <span asp-validation-for="DepartmentID" class="text-danger"></span>
    <br />

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

EMS_MVC/Views/Employee/ViewAllEmployees.cshtml
@model List<Employee>


<h3 align="center">Employees List</h3>

<a class="btn btn-success" asp-action="AddEmployee" asp-controller="Employee">Add Employee</a>

<table class="table table-striped table-info">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Date of Birth</th>
            <th scope="col">Email Address</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Department</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Emp in Model)
        {
            /*string deptname = "";
            int counter = 0;
            foreach(var item in ViewBag.Departments)
            {
                if(Emp.ID == ViewBag.Departments[counter].ID){
                    deptname = ViewBag.Departments[counter].Name;
                }
                counter++;
            }*/
            <tr>
                <th scope="row">@Emp.ID</th>
                <td>@Emp.Name</td>
                <td>@Emp.DateOfBirth</td>
                <td>@Emp.Email</td>
                <td>@Emp.Phone</td>
                <td>@Emp.Department.Name</td>
                <td><a class="btn btn-primary" asp-controller="Employee" asp-action="ViewOneEmployee" asp-route-id="@Emp.ID">View</a></td>
                <td><a class="btn btn-warning" asp-controller="Employee" asp-action="UpdateEmployee" asp-route-id="@Emp.ID">Edit</a></td>
                <td><a class="btn btn-danger" asp-controller="Employee" asp-action="DeleteEmployee" asp-route-id="@Emp.ID">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

EMS_MVC/Views/Employee/ViewOneEmployee.cshtml
@model Employee

<h1>Employee Details</h1>

<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <h6 class="card-subtitle mb-2 text-muted">@Model.ID</h6>
        <h5 class="card-text">@Model.DateOfBirth</h5>
        <h5 class="card-text">@Model.Email</h5>
        <h5 class="card-text">@Model.Phone</h5>
        <h5 class="card-text">@Model.Department.Name</h5>
        <a asp-controller="Employee" asp-action="ViewAllEmployees" class="card-link">Back to list</a>
    </div>
</div>

EMS_MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EMS_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMS_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EMS_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EMS_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="ViewAllEmployees">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="ViewAllDepartments">Departments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EMS_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>